name: Snake Game

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake (Dark Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: jeminerv
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-game.svg?color_snake=#00ff88&color_dots=#222222,#444444,#666666,#888888,#aaaaaa

      - name: Push Snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
